### PR TITLE
Update get connected tweet list

### PR DESCRIPTION
**Pull request by hluko**
**Updated Page:** 
https://www.fivefifthsvoter.com/#/connect
localhost:3000/connect

- Added color legend for sentiments
- Added sentiment color border for tweets

**Before:** 
image

**After:**
MicrosoftTeams-image

### CODE REVIEW

**Comment by henryn098** [comment]
OSes: Windows and MacOS
Browsers: Chrome, Firefox and Safari

As for coverage testing, I agree. My team isn't super familiar with it so we might need a bit of guidance. I think we also need to tweak the sentiments legend to make it more mobile-friendly.

**Review by GeraldMit — APPROVED** [review]

**Comment by krook** [comment]
Looks like this has merge conflicts @hluko. Can you please attempt the recommended steps above to resolve?

**Comment by krook** [comment]
I'm working to resolve. I took the change, manually applied it to `main`. So therefore this pull request can be closed. Can you please try to rebase it before I do that?

**Comment by henryn098** [comment]
Done! Sorry for the delay, it took me a while to learn how to rebase.

**Comment by krook** [comment]
No problem @henryn098, thanks for the contribution! I replied in the other PR, but looks like this one will work instead?

**Comment by henryn098** [comment]
Yeah, since the changes for the other PR were manually made to main, it showed 0 changed files so I think it's obsolete.

**Comment by krook** [comment]
Cool, so it looks like we're all set now.

**Comment by davidnixon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/29862df8-a9ad-4d66-9e9f-fb7dbf74687b?env_id=ibm:yp:us-south "five-fifths-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/73b7a52e-0040-410e-9226-2e9b8435c37a "five-fifths-voter-pipeline") deployed [Five-Fifths-Voter](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/releases/tag/deploy-ibm-yp-us-south-cfc-team-external-apps-cfc-fivefifths-space-20210809-013010 "deploy-ibm-yp-us-south-cfc-team-external-apps-cfc-fivefifths-space-20210809-013010") to [cfc-fivefifths-space](https://console.bluemix.net/apps/8c251f3c-ac6d-42c1-b64c-cf383c9925bb?env_id=ibm:yp:us-south "ibm:yp:us-south:cfc-team-external-apps:cfc-fivefifths-space"), including commit 9dba0d2e6efabb53d1a0b97fd229304038d0410c

**Pull request merged**
