### PR TITLE
Map and voter ID updates

### PR DESCRIPTION
**Pull request by davidnixon**
feat(voterid): Add voterid API and and use of it to the Get Informed Page
## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Locally in dev env

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

Signed-off-by: David Nixon <david_nixon@us.ibm.com>

### CODE REVIEW

**Comment by davidnixon** [comment]
@annumberhocker this is a noisy PR. On the UI side the interesting bit is here to load the voter id json for the API
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L154-L164

So that loads all the data we have for all states/territories.
Then in the `onChange` I set the specific data for the state
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L172-L174

And then in the template there is just an if ... else to either display the data we have or if no data is available it displays the general requirements that were already there.
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L69-L72

https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L87-L92

Let me know if that looks OK to you. I know we are redesigning the page but I do expect voter id stuff will be part of new design somewhere. I did not do anything with the button that links to vote411.

**Comment by davidnixon** [comment]
@annumberhocker @GeraldMit @sydbails The design for this API is pretty simplistic so let me know if its ok with you guys.
1. A human person has to find the voter id info on each state site. 
1. The human person makes json file like this:
```json
{
  "info": "https://elections.delaware.gov/information/faq/voting.shtml",
  "list": [
    "Delaware Drivers License or State ID",
    "U. S. Passport",
    "Signed Polling Place or Social Security Card",
    "Signed vehicle registration",
    "Signed credit card with photo",
    "A similar document that identifies the person by photo or signature"
  ],
  "notes": "Do I have to show ID to vote? No, but, poll workers will ask you to show proof of identity. If you do not show ID, you must fill out a form before you can vote. Showing ID makes checking you in faster and reduces mistakes.",
  "more_info": "https://ivote.de.gov/VoterView",
  "date_gathered": "2020-10-25"
}
```
Where info is the exact link to the document on the state's site and more_info is a more general link to something that makes sense. date_gathered is whatever date the human person got the info from the state's site. And list is just a list of ids.
1. Those json files are gathered in `services/data/voterid/`
1. And consolidated in `services/data/voterid/index.js`
1. And delivered by the API with a GET to  `/voterid`


On our site I have it displaying like this:
- link to "State voter ID information" the href is `info`
  https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L70-L72
- (Validated `date_gathered` )
  https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L74-L75
- `stateVoterIdData.notes`
  https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L77
- list of ids
  https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L79-L81
- link to "More Information from your State" the href is `more_info`
  https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/6f68c6ba4c496cecdd6598888b341b42547b1b9a/src/components/VoteNow/VoteNow.vue#L83-L85

I have done Alabama though Kansas so if this looks ok to you guys I'll get the rest or I might ask some of the others guys to help divide the work.

**Comment by GeraldMit** [comment]
I think notes and more_info should be arrays for future proofing, I think it is good.

**Comment by cstefano1** [comment]
Wisconsin:

•	https://myvote.wi.gov/en-us/PhotoIDRequired

Valid IDs:
•	A Wisconsin DOT-issued driver license, even if driving privileges are revoked or suspended - Can be unexpired or expired after Nov 18, 2018
•	A Wisconsin DOT-issued identification card - Can be unexpired or expired after Nov 18, 2018
•	A Military ID card issued by the U.S. Uniformed Services (including retired and dependent uniformed service IDs) - Can be unexpired or expired after Nov 18, 2018
•	A U.S. passport book or card - Can be unexpired or expired after Nov 18, 2018
•	A certificate of naturalization (that was issued no earlier than two years before the date of the election)
•	An identification card issued by a federally recognized Indian tribe in Wisconsin (can be expired or unexpired)
•	A driver license receipt issued by Wisconsin DOT (valid for 45 days from date issued)
•	An identification card receipt issued by Wisconsin DOT (valid for 45 days from date issued)
•	A Wisconsin DMV ID Petition Process Photo Receipt (valid for 60 days from date issued)
•	A Veteran Affairs ID card (must be unexpired or have no expiration date)
•	A photo identification card issued by a Wisconsin accredited university or college, or technical college that contains the following: Date the card was issued, Signature of student, Expiration date no later than two years after date of issuance (card may be expired). The university or college ID must be accompanied by a separate document that proves enrollment, such as a tuition fee receipt, enrollment verification letter, or class schedule.  Enrollment verification document can be shown electronically.

•	Notes: You can get a free Wisconsin State ID card at the Division of Motor Vehicles.  Poll workers look at the following:  The photograph must reasonably resemble the elector. The elector’s name must conform to the name on their voter registration; conform does not mean that the name must be identical to the name on the voter registration. If the ID has an expiration date, it must meet the expiration requirements listed. An acceptable Photo ID for voting does not have to include a current address. You only prove your address when registering.

•	https://bringit.wi.gov/
•	https://myvote.wi.gov/en-us/

•	10/30/2020

**Comment by cstefano1** [comment]
Michigan

https://www.michigan.gov/sos/0,4670,7-127-1633_8716-178123--,00.html

IDs:
Michigan driver’s license
Michigan personal identification card (state ID)
Current driver’s license or personal ID card issued by another state. 
Current Federal or state government-issued photo ID. 
Current U.S. passport. 
Current Military identification card with photo. 
Current Student identification with photo from a high school or an accredited institution of higher education. 
Current Tribal identification card with photo.

Notes:
Your ID does not need to show your address.  If you do not have photo ID, you can still cast a ballot by signing an affidavit. The affidavit can be used by voters who do not have acceptable photo ID or voters who have photo ID but didn't bring it to the polls.  Once you sign the affidavit, you may cast your ballot. It will be counted with all other ballots on Election Day.
If you do not have a driver's license or other acceptable photo identification, you can get a state identification card at your local Secretary of State branch office for $10.  State ID cards are free to individuals who are 65 or older or who are blind. Cards are also free to those who have had driving privileges terminated due to a physical or mental disability. The fee can also be waived for individuals who present other good cause for a fee waiver.

Links
•	https://mvic.sos.state.mi.us/Home/VoteInPerson
•	https://mvic.sos.state.mi.us/Home/Index
•	No-fee state ID card policy: https://www.michigan.gov/sos/0,4670,7-127-1627_8668_9059-228283--,00.html

10/30/2020

**Comment by cstefano1** [comment]
https://www.sos.la.gov/ElectionsAndVoting/Vote/VoteOnElectionDay/Pages/default.aspx

IDs
•	a driver's license
•	a Louisiana Special ID
•	LA Wallet digital driver's license
•	a United States military identification card that contains the applicant's name and picture
•	some other generally recognized picture ID that contains your name and signature

Notes:
If you do not have one of the acceptable forms of ID, you may still cast your vote by signature on a voter affidavit.  
You may get a free Louisiana Special ID at the Office of Motor Vehicles by showing your voter information card.  If you have misplaced your voter information card, contact your registrar of voters for a new one or print your own by logging into the Louisiana Voter Portal as a voter. Click the 'Voter Registration' tab at the top then click the 'Print Voter Information' link located on the ribbon on the left-hand side.

Links:
https://voterportal.sos.la.gov/
https://voterportal.sos.la.gov/registrar

10/30/2020

**Comment by cstefano1** [comment]
Maine
https://www.maine.gov/sos/cec/elec/voter-info/right.html

IDs
There is no voter ID requirement in Maine.

Notes:
If you register to vote on election day, show ID and proof of residence. See Voter Registration information for details.

Links:

https://www.maine.gov/sos/cec/elec/voter-info/voterguide.html
https://www.maine.gov/sos/cec/elec/voter-info/votreg.html

10/30/2020

**Comment by cstefano1** [comment]
_Maryland is confusing -- dunno if this will easily fit the planned format._

**Maryland**
https://www.marylandattorneygeneral.gov/Pages/votingFAQ.aspx#7

ID 
Usually, you will not be asked to show ID if your name is on the list of registered voters. 
However, you will be asked to show ID if (1) you registered by mail and have not previously met the identification requirements, (2) someone in the polling place challenges your identity, or (3) you are registering to vote during early voting or changing your address during early voting.
•	A Maryland Driver's License or other Motor Vehicle Administration (MVA) issued identification
•	A student ID card that contains a photo
•	An employee ID card that contains a photo
•	A passport or other government issued ID
•	If you do not have those forms of ID: a utility bill, bank statement, government check or paycheck that shows your name and address and is less than 3 months old. If you are showing ID because you are voting for the first time, your name and address on the document must match the information on the voter registration roll.
Notes:
If you do not have your ID with you, you may vote a provisional ballot for the presidential general election and bring your ID to your local election board before 10 a.m. on November 12, 2020, so that your identity and eligibility can be verified in time to count your vote.

Links:
https://www.marylandattorneygeneral.gov/Pages/votingFAQ.aspx

10/30/2020

**Comment by cstefano1** [comment]
Massachusetts
https://www.sec.state.ma.us/ele/eleidreq/idrequirementsidx.htm

IDs
•	Identification must include your name and the address at which you are registered to vote. 
•	Driver's license
•	State-issued ID card
•	Recent utility bill
•	Recent rent receipt
•	A lease
•	A copy of a voter registration affidavit
•	Any other printed identification which contains the voter's name and address

Notes:
You may be asked to show identification when you check-in at your polling place for any of the following reasons:
•	You are voting for the first time in Massachusetts in a federal election
•	You are voting for the first time in a federal election in Massachusetts after registering to vote by mail
•	You are an inactive voter
•	You are casting a provisional or challenged ballot
•	The poll worker has a reasonable suspicion that leads them to request identification

If you are unable to present identification when you check-in, you may cast a provisional ballot and return later with identification. If you do not return with acceptable identification by close of polls, your ballot cannot be counted.
If you an inactive voter or a poll worker requests identification and you are not able to present it, you must still be permitted to vote; however, your ballot must be challenged. This means that your name and address, the name and address of the challenger, and the reason for the challenge must be written on your ballot. You ballot will be cast normally and will only be re-examined in the case of a recount, court order, or audit.

Links:
https://www.sec.state.ma.us/ele/eleidx.htm

10/30/2020

**Comment by drealuc** [comment]
Completed Minnesota, Mississippi, Missouri, Montana, Virginia
[Andrea state info list.docx](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/files/5471434/Andrea.state.info.list.docx)

**Comment by cstefano1** [comment]
Oklahoma
https://www.ok.gov/elections/Voter_Info/Proof_of_Identity/

ID:
Photo ID:  This must have been issued by the United States government, the State of Oklahoma, or a federally recognized tribal government.  It must contain (1) The name of the person to whom it was issued (2) A photograph of the person to whom it was issued (3)  An expiration date that is after the date of the election, unless the identification is valid indefinitely
County Election Board Voter ID Card: This ID free and is received by mail from the County Election Board after voter registration.  This can be used even though it does not include a photograph.
Affidavit: If you do not have or if you refuse to show proof of identity, you may vote by provisional ballot and prove your identity by signing a sworn affidavit. 

Notes:

The law requires the voter's name on the proof of identity document to "substantially conform" to the voter's name in the Precinct Registry.  In other words, your name on your proof of identity must match your name in the Precinct Registry.
Provisional ballots are sealed inside special envelopes and are not put through the voting device.  After election day, County Election Board officials will investigate the information provided by the voter on the affidavit and either will approve the provisional ballot for counting or will reject it based on the outcome of that investigation.

A provisional ballot cast by a voter who declines or is unable to produce proof of identity shall only be considered verified and approved for counting if: (1) The voter's name on the affidavit substantially conforms to the voter's name in the voter registration database. (2) The voter's residence address on the affidavit substantially conforms to the voter's residence address in the voter registration database. (3) The voter's date of birth matches the information in the voter registration database. (4) The voter's Oklahoma driver license number or the last four digits of the voter's Social Security number on the affidavit matches the information in the voter registration database.  (This provision does not apply if the voter was not required to provide a driver license number or the last four digits of the voter's Social Security number at the time of registration.) (5) The provisional ballot meets the eligibility requirements set forth in Section 7-116.1 of Title 26 of the Oklahoma Statues.

Links:
https://www.ok.gov/elections/index.html
https://www.ok.gov/elections/faqs.html#q1369
11/1/2020

**Comment by cstefano1** [comment]
Pennsylvania
https://www.votespa.com/Register-to-Vote/Pages/Voter-ID-for-First-Time-Voters.aspx

IDs
•	Only voters who are voting for the first time in their election district need to show ID. The ID does not need to include a photograph but must include name and address.
•	Driver’s license or PennDOT ID card
•	U.S. passport
•	Military, student, or employee ID
•	Voter registration card
•	Firearm permit
•	Current utility bill, bank statement, paycheck or government check
•	Any ID issued by the commonwealth or federal government
•	Confirmation issued by the County Voter Registration Office

Notes:
If you have voted at your polling location before, you do not need to bring an ID to vote.

Links:
https://www.pa.gov/guides/voting-and-elections/
11/1/2020

**Comment by cstefano1** [comment]
Texas
https://www.votetexas.gov/mobile/id-faqs.htm

ID
Texas Driver License issued by the Texas Department of Public Safety (DPS)
Texas Election Identification Certificate issued by DPS
Texas Personal Identification Card issued by DPS
Texas Handgun License issued by DPS
United States Military Identification Card containing the person’s photograph
United States Citizenship Certificate containing the person’s photograph
United States Passport (book or card)

Notes
For voters aged 18 – 69 years, photo ID can be expired for up to four years. For voters aged 70 and older, photo ID can be expired for any length of time if otherwise valid.

If you do not possess and cannot reasonably obtain one of the acceptable forms of ID, you may qualify for a Reasonable Impediment Declaration by showing a copy or original of one of the following approved IDs: Certified Domestic Birth Certificate or Court Admissible Birth Document, Paycheck, Government document with your name and address including your Voter Registration Certificate, Current Utility Bill, Bank Statement, Government Check

Voters with a disability may apply with the county voter registrar for a permanent exemption to presenting an acceptable photo identification or following the Reasonable Impediment Declaration procedure in the county. 

Voters who have a consistent religious objection to being photographed or who do not present an acceptable form of photo identification listed above or follow the Reasonable Impediment Declaration procedure because of certain natural disasters as declared by the President of the United States or the Texas Governor, may vote a provisional ballot, appear at the voter registrar’s office within six (6) calendar days after election day, and sign an affidavit swearing to the religious objection or natural disaster, in order for the voter’s ballot to be counted. Please contact your county voter registrar for more details.

Links
https://www.votetexas.gov/docs/sos-voter-ed-8-5x14-poster-eng.pdf

11/1/2020

**Comment by cstefano1** [comment]
South Carolina
https://www.scvotes.gov/node/235

ID
SC Driver's License - Includes standard license and REAL ID
SC Department of Motor Vehicles ID Card - Includes standard ID card and REAL ID and  SC Concealed Weapons Permit
SC Voter Registration Card with Photo
Federal Military ID - Includes all Department of Defense Photo IDs and Veterans Affairs Benefits Card
US Passport - Includes US Passport ID Card

Notes
You can get a free Photo ID from your county voter registration and elections office or your local DMV office.

If you're already registered to vote, go to your county voter registration and elections office, provide your date of birth and the last four digits of your Social Security Number.  Then, have your photo taken. If you are not yet registered, you need to register to vote first.  You can register and have your photo taken on the same day.   

To learn how to get a DMV ID card, call or visit your local DMV office or visit scdmvonline.com.

If you forget to bring your photo ID to your polling place, you may vote a provisional ballot that will count only if you show your Photo ID to the election commission prior to certification of the election (usually Thursday or Friday after the election).

If you can’t get a photo ID, bring your non-photo voter registration card with you to the polling place.  You may vote a provisional ballot after signing an affidavit stating you have a reasonable impediment to obtaining Photo ID.  A reasonable impediment is any valid reason, beyond your control, which created an obstacle to obtaining a Photo ID. Some examples include a disability or illness, a conflict with your work schedule, a lack of transportation, a lack of a birth certificate, family responsibilities, a religious objection to being photographed, any other obstacle you find reasonable.  This ballot will count unless someone proves to the election commission that you are lying about your identity or about having the listed impediment.

To vote under the reasonable impediment exception, inform the poll managers that you do not have a photo ID and could not get one; present your current, non-photo registration card, sign the affidavit provided by the poll managers stating why you could not obtain a Photo ID, cast a provisional ballot that will be counted unless the county election commission has reason to believe your affidavit is false.

Links
https://www.scvotes.gov/
scdmvonline.com

11/1/2020

**Comment by cstefano1** [comment]
Tennessee
https://sos.tn.gov/products/elections/what-id-required-when-voting

IDs
Any of the following IDs may be used, even if expired.
Tennessee driver license with your photo
United States Passport (book or card)
Photo ID issued by the Tennessee Department of Safety and Homeland Security
Photo ID issued by the federal or Tennessee state government
United States Military photo ID
Tennessee handgun carry permit with your photo

Notes
If you are voting in your first Federal election and you registered by mail, you must present a current photo identification with voter’s name and photo.  If the photo identification is expired, the voter must also present one of the following: a copy of a current utility bill, bank statement, government check, paycheck or other government document that shows the voter’s name and address.

The following IDs are not acceptable:  College student IDs and photo IDs not issued by the federal or Tennessee state government. This includes county or city issued photo IDs, such as library cards, and photo IDs issued by other states.

These voters are exempt from the ID requirement: Voters with a religious objection to being photographed; Voters who are indigent and unable to obtain a photo ID without paying a fee.

If you don’t bring a photo ID, you will vote a provisional ballot. You will then have two (2) business days after Election Day to return to the election commission office to show a valid photo ID. Upon returning to the election commission office, the voter will sign an affidavit and a copy of the voter’s photo ID will be made to be reviewed by the counting board.

You may obtain a free photo ID to vote from the Department of Safety and Homeland Security at any participating driver service center across the state. You may use the “express service” line at the driver service center to obtain your photo ID to minimize wait times. Visit the Department of Safety and Homeland Security's Voter Photo ID page for more information.


Links
https://sos.tn.gov/products/elections-executive/nov-3-election-information
https://www.tn.gov/safety/driver-services/photoids.html

11/1/2020

**Comment by cstefano1** [comment]
Oregon
https://sos.oregon.gov/voting/Pages/voteinor.aspx

ID
Oregon has no voter ID requirement.

Notes
All voting in Oregon is by mail

Links
https://secure.sos.state.or.us/orestar/vr/register.do

11/1/2020

**Review by annumberhocker — APPROVED** [review]
lgtm

**Pull request merged**
