### PR TITLE
fixes #209

### LINKED ISSUE #209: Accessibility Unit Testing
### Background on the problem the feature will solve/improved user experience
Five Fifths Voter users with accessibility needs should be able to use our solution without limitations. 

### Describe the solution you'd like
Unit testing is needed to identify if [Level 1 accessibility](https://www.ibm.com/able/requirements/requirements/-) requirements are met. IBM has a robust process for guaranteeing accessibility athttps://www.ibm.com/able/. This is publicly available as a reference for creating, designing, and testing for accessibility needs. 

### Tasks 
- Unit test of 5/5 voter website (can use https://www.ibm.com/able/toolkit/verify) 
- Check against [Level 1 accessibility requirements](https://www.ibm.com/able/requirements/requirements/-) [select Level 1 in Level to Achieve on left hand side filter pane]

### Acceptance Criteria 
- Checklist of Level 1 accessibility requirements met or failed 
- Path forward to meeting 75% of the 21 requirements under Level 1

### PR DESCRIPTION
**Pull request by Fiewor**

### CODE REVIEW

**Review by davidnixon — CHANGES_REQUESTED** [review]
This looks like it will work but there are 2 syntax error.
Can you install yarn https://yarnpkg.com/lang/en/docs/cli/install/
and in the ui directory run 
```sh
yarn
yarn serve
```
It will show the errors there. 
Extra `};` in AppHeader and some unresolved conflicts in Hero.
For Hero I think you want
```
      <div class="hero__content" role="contentinfo">
        <h1 class="hero__heading">{{ $t('welcomeMsg', ['Five Fifths Voter']) }}</h1>
```

**Comment by davidnixon** [comment]
Forgot to mention. You might want `nvm` as well.
https://github.com/nvm-sh/nvm

```sh
nvm install 14
```

**Comment by upkarlidder** [comment]
@davidnixon this is a great use case for adding GitHub action that simply does "yarn build" and the PR cannot be merged until that is resolved.

I can create an issue if you agree. Another good first issue 🎉

**Comment by Fiewor** [comment]
hey @davidnixon  @upkarlidder mind reviewing it now? It looks fine at my end

**Comment by davidnixon** [comment]
> @davidnixon this is a great use case for adding GitHub action that simply does "yarn build" and the PR cannot be merged until that is resolved.
> 
> I can create an issue if you agree. Another good first issue 🎉

Yes that would be great thanks @upkarlidder 

@Fiewor reviewing now ...

**Review by davidnixon — CHANGES_REQUESTED** [review]
Something has gone wrong 😉 
image

I don't think the intent was to change 1.5k files. I have seen this before but I do not know why exactly it happens. May I ask what OS you are using? I'm on OSx and Ubuntu and I cannot reproduce this there. So I think maybe windows?

So the immediate issue is that the yarn cache files are included in this PR. To resolve that, try this:
```
cd ui
git rm -f -r .yarn
git rm .yarnrc.yml
git commit -s -m "remove yarn cache file"
git push
```

There are 2 root issues.
- the top level `.gitignore` should exclude .yarn - I'll fix this so that other do not run into this issue
- Your yarn cache dir should not be in the `ui` dir. To fix that try this:
    ```sh
    yarn cache dir # this should show where yarn want to put cache files. Probably it will say  .../ui/.yarn
    yarn config set cache-folder ~/.yarn # Linux/OSX
    yarn config set cache-folder C:\Users\Yourname\.yarn # windows - probably work but I have not tested it 
    yarn cache dir # should show new dir
    ```
https://classic.yarnpkg.com/en/docs/cli/cache/

**Comment by davidnixon** [comment]
Oh I see what's happening. This is a yarn version 1 .x vs yarn version 2.x issue. In yarn 2 apparently the cache folder is exactly where is it supposed to be in the `ui/.yarn/cache` folder. I have upgraded my yarn version locally.

**Comment by upkarlidder** [comment]
@davidnixon does this need to go into .gitignore or is it like package-lock.json and gets checked in?

**Comment by davidnixon** [comment]
@upkarlidder I'm going to update gitignore based on the recommendations here https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

**Comment by Fiewor** [comment]
Sorry. Just seeing this @davidnixon What changes am I to make?

**Comment by Fiewor** [comment]
> I don't think the intent was to change 1.5k files. I have seen this before but I do not know why exactly it happens. May I ask what OS you are using? I'm on OSx and Ubuntu and I cannot reproduce this there. So I think maybe windows?

Yes, I'm using Windows

**Comment by Fiewor** [comment]
> So the immediate issue is that the yarn cache files are included in this PR. To resolve that, try this:
> 
> ```
> cd ui
> git rm -f -r .yarn
> git commit -s -m "remove yarn cache file"
> git push
> ```
Just to confirm, should I still go ahead with this step?

**Comment by Fiewor** [comment]
> > So the immediate issue is that the yarn cache files are included in this PR. To resolve that, try this:
> > ```
> > cd ui
> > git rm -f -r .yarn
> > git commit -s -m "remove yarn cache file"
> > git push
> > ```
> 
> Just to confirm, should I still go ahead with this step?

Done!

**Comment by upkarlidder** [comment]
Files changed went to 6! That's a good sign that it worked. Thank you @Fiewor 🎉

**Review by davidnixon — CHANGES_REQUESTED** [review]
Thank you for removing the cache files! 😉 That makes it much easier to review. This is very close to mergable.
1. Can you run `yarn lint` that will fix up the indentation warnings that are shown. If you have vscode or atom you can install the prettier plugin and enable it. Otherwise just always run `yarn lint` before check in. @upkarlidder it would be great to get a commit hook that will run this automatically. I know that https://github.com/carbon-design-system/carbon-components-vue has this implemented so maybe we can copy it from there.
2. The checker complains that `role="content info"` 
    > The 'role' defined on the element is not valid per ARIA specification
    
    https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
    so it shoudl be `contentinfo`
    Unfortunately when I set it to "contentinfo" the checker then says
    > Multiple elements with "contentinfo" role do not have unique labels

    So it looks like we need `aria-label` on both the `contentinfo` elements in Hero.vue. I suggest `aria-label="hero image"` for the first and `aria-label="hero quote"` for the second.
1. Last thing. I don't think we saw this one before but there is a new checker complaint. 
    > Content is not within a landmark element 

    It is complaining about this element in the header area. `<router-link class="bx--feature-card__link" to="/whyvote">` I think this is a new button? In any case the enclosing div needs to be marked as navigation. Like this:
    ```vue
    <div
        class="bx--row bx--feature-card__row"
        role="navigation"
        aria-label="quick link to why vote"
      >
    ```

**Comment by Fiewor** [comment]
> Thank you for removing the cache files! 😉 That makes it much easier to review. This is very close to mergable.
> 
> 1. Can you run `yarn lint` that will fix up the indentation warnings that are shown. If you have vscode or atom you can install the prettier plugin and enable it. Otherwise just always run `yarn lint` before check in. @upkarlidder it would be great to get a commit hook that will run this automatically. I know that https://github.com/carbon-design-system/carbon-components-vue has this implemented so maybe we can copy it from there.
> 2. The checker complains that `role="content info"`
>    > The 'role' defined on the element is not valid per ARIA specification
>    
>    
>    https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
>    so it shoudl be `contentinfo`
>    Unfortunately when I set it to "contentinfo" the checker then says
>    > Multiple elements with "contentinfo" role do not have unique labels
>    
>    
>    So it looks like we need `aria-label` on both the `contentinfo` elements in Hero.vue. I suggest `aria-label="hero image"` for the first and `aria-label="hero quote"` for the second.
> 3. Last thing. I don't think we saw this one before but there is a new checker complaint.
>    > Content is not within a landmark element
>    
>    
>    It is complaining about this element in the header area. `<router-link class="bx--feature-card__link" to="/whyvote">` I think this is a new button? In any case the enclosing div needs to be marked as navigation. Like this:
>    ```
>    <div
>        class="bx--row bx--feature-card__row"
>        role="navigation"
>        aria-label="quick link to why vote"
>      >
>    ```

I've done this and committed, but it doesn't seem to be reflecting in the PR like the previous commits did. I can't quite figure out where I missed it.

**Comment by Fiewor** [comment]
I have resolved it, but now failing the DCO check (I keep forgetting to  add the -s flag while committing) even though I have followed the instructions stated under the details of the DCO

**Review by davidnixon — APPROVED** [review]
image

Nice!

**Comment by davidnixon** [comment]
> I have resolved it, but now failing the DCO check (I keep forgetting to add the -s flag while committing) even though I have followed the instructions stated under the details of the DCO

I don't know why DCO fails sometimes. I'll override it.
image

**Pull request merged**
