### PR TITLE
ui(i18n): fixing translation keys removing the dot notation

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Contributes to #288 

## What did you do?

- ui(i18n): fixing translation keys removing the dot notation

## Why did you do it?

The translation strings are not working with the "dot" notation in their key.
https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [x] N/A

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by upkarlidder** [comment]
Thanks @dennybiasiolli. Is it standard to use underscore in vue and not the dot notation? I did translations a while ago and we used the dot notation and so I stuck that that. Wondering the reason to use underscore. Thanks.

**Comment by dennybiasiolli** [comment]
> Thanks @dennybiasiolli. Is it standard to use underscore in vue and not the dot notation? I did translations a while ago and we used the dot notation and so I stuck that that. Wondering the reason to use underscore. Thanks.

Well, you can also use the dot notation, but in that case you have to change the translation files acting like objects.
Check more here: https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

**Comment by dennybiasiolli** [comment]
You can use them with the dot notation changing translation files from

```json
  "getInformedDisplay.1": "Acceptable IDs",
  "getInformedDisplay.2": "State voter ID information",
  "getInformedDisplay.3": "More Information from your State",
  "getInformedDisplay.4": "State Voting Info",
```

to

```json
  "getInformedDisplay": {
    "1": "Acceptable IDs",
    "2": "State voter ID information",
    "3": "More Information from your State",
    "4": "State Voting Info"
  },

**Comment by davidnixon** [comment]
@upkarlidder I agree with @dennybiasiolli here. The underscore is better for these particular strings. A nicer why to group the string would be as suggested:

```json
  "getInformedDisplay": {
    "1": "Acceptable IDs",
    "2": "State voter ID information",
    "3": "More Information from your State",
    "4": "State Voting Info"
  },

```

But in that case I don't think 1,2,3,4 would be used. Instead maybe "acceptable", "stateId", "moreInfo", "stateInfo".

**Review by davidnixon — APPROVED** [review]

**Comment by davidnixon** [comment]
@upkarlidder lmk what you think. The newer Spanish translation are causing a merge conflict here but I'll resolve that with when I merge this PR.

**Comment by dennybiasiolli** [comment]
@davidnixon I can rebase this PR if you want 😉

**Comment by upkarlidder** [comment]
Sounds good. We also have new translations. We can add that after merging this here. 
Thank you @dennybiasiolli!

**Pull request merged**
