### PR TITLE
Updating copy to page

### PR DESCRIPTION
**Pull request by devineam**
## Description
Changed "adress" to "address"
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Tested in dev environment

## Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by davidnixon** [comment]
I have a theory on the contributors page issue.
Screen Shot 2020-10-21 at 7 55 02 AM
For this one I'm going to use "create merge commit"
Screen Shot 2020-10-21 at 7 56 23 AM

**Comment by davidnixon** [comment]
I still don't see @devineam in the contributors list. :-( Maybe it will update later.

**Comment by devineam** [comment]
@davidnixon I have been committing from my public account and not my private one, but they should be merged.

**Comment by davidnixon** [comment]
@sydbails @devineam Found this doc: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile

I think Alex mentioned this already but check your github email https://github.com/settings/emails and make sure it matches whatever is shown when you do `git config user.email` on the terminal command line.

**Pull request merged**
